import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  bookSidebar: [
    {
      type: 'category',
      label: '📖 Introduction: The Reality Check',
      link: {type: 'doc', id: 'intro/reality-check'},
      items: [
        'intro/reality-check',
        'intro/junior-crisis',
        'intro/who-is-at-risk',
        'intro/vibe-coding',
        'intro/new-identity',
        'intro/how-this-book-saves-you',
      ],
    },
    {
      type: 'category',
      label: '🧠 Part 1: How to Think',
      link: {type: 'doc', id: 'part-1-how-to-think/art-of-questioning'},
      items: [
        'part-1-how-to-think/art-of-questioning',
        'part-1-how-to-think/prediction-lock',
        'part-1-how-to-think/divergence-test',
        'part-1-how-to-think/detecting-broken-reasoning',
        'part-1-how-to-think/first-principles',
        'part-1-how-to-think/systems-thinking',
        'part-1-how-to-think/second-order-thinking',
        'part-1-how-to-think/communicating-what-matters',
        'part-1-how-to-think/working-with-ai',
        'part-1-how-to-think/ethical-reasoning',
        'part-1-how-to-think/deciding-under-uncertainty',
        'part-1-how-to-think/learning-how-to-learn',
      ],
    },
    {
      type: 'category',
      label: '🔄 Part 2: System Thinking',
      link: {type: 'doc', id: 'part-2-system-thinking/cascade-mapping'},
      items: [
        'part-2-system-thinking/cascade-mapping',
        'part-2-system-thinking/feedback-loops',
        'part-2-system-thinking/human-vs-ai-systems',
        'part-2-system-thinking/leverage-points',
        'part-2-system-thinking/emergent-behavior',
        'part-2-system-thinking/variable-shift',
      ],
    },
    {
      type: 'category',
      label: '🧱 Part 3: Logic Building',
      link: {type: 'doc', id: 'part-3-logic-building/timeless-fundamentals'},
      items: [
        'part-3-logic-building/timeless-fundamentals',
        'part-3-logic-building/python-deep-dive',
        'part-3-logic-building/c-truth-serum',
        'part-3-logic-building/algorithms-that-matter',
        'part-3-logic-building/data-structures-ai-cant-replace',
        'part-3-logic-building/avoiding-vibe-coding',
      ],
    },
    {
      type: 'category',
      label: '🏗️ Part 4: System Design',
      link: {type: 'doc', id: 'part-4-system-design/agentic-architecture'},
      items: [
        'part-4-system-design/agentic-architecture',
        'part-4-system-design/multi-agent-patterns',
        'part-4-system-design/intent-driven-design',
        'part-4-system-design/hybrid-deployment',
        'part-4-system-design/mcp-connectors',
        'part-4-system-design/rag-systems',
        'part-4-system-design/evaluation-frameworks',
        'part-4-system-design/security-by-design',
      ],
    },
    {
      type: 'category',
      label: '🐛 Part 5: Debugging',
      link: {type: 'doc', id: 'part-5-debugging/mental-stack-trace'},
      items: [
        'part-5-debugging/mental-stack-trace',
        'part-5-debugging/probabilistic-qa',
        'part-5-debugging/ai-error-patterns',
        'part-5-debugging/debugging-ai-breaks',
        'part-5-debugging/code-review-ai',
        'part-5-debugging/production-debugging',
      ],
    },
    {
      type: 'category',
      label: '🤖 Part 6: AI + Agents',
      link: {type: 'doc', id: 'part-6-ai-agents/cursor-vs-copilot-vs-claude'},
      items: [
        'part-6-ai-agents/cursor-vs-copilot-vs-claude',
        'part-6-ai-agents/custom-agents',
        'part-6-ai-agents/knowing-when-wrong',
        'part-6-ai-agents/director-mindset',
        'part-6-ai-agents/tool-selection-matrix',
        'part-6-ai-agents/prompt-engineering',
        'part-6-ai-agents/agent-orchestration',
        'part-6-ai-agents/ai-workflow-automation',
      ],
    },
    {
      type: 'category',
      label: '🧩 Part 7: Problem Solving',
      link: {type: 'doc', id: 'part-7-problem-solving/decomposition'},
      items: [
        'part-7-problem-solving/decomposition',
        'part-7-problem-solving/decision-frameworks',
        'part-7-problem-solving/domain-workflows',
        'part-7-problem-solving/ten-x-workflow',
        'part-7-problem-solving/root-cause-analysis',
        'part-7-problem-solving/creative-solutions',
      ],
    },
    {
      type: 'category',
      label: '💼 Part 8: Business & Career',
      link: {type: 'doc', id: 'part-8-business-thinking/roi-thinking'},
      items: [
        'part-8-business-thinking/roi-thinking',
        'part-8-business-thinking/global-salary-benchmarks',
        'part-8-business-thinking/freelancing-ai-expert',
        'part-8-business-thinking/building-saas',
        'part-8-business-thinking/personal-brand',
        'part-8-business-thinking/networking-ai-era',
        'part-8-business-thinking/continuous-learning',
        'part-8-business-thinking/survival-roadmap',
      ],
    },
    {
      type: 'category',
      label: '🚀 Part 9: Build → Deploy → Show',
      link: {type: 'doc', id: 'part-9-build-deploy-show/build-real-projects'},
      items: [
        'part-9-build-deploy-show/build-real-projects',
        'part-9-build-deploy-show/deploy-publicly',
        'part-9-build-deploy-show/power-of-open-source',
        'part-9-build-deploy-show/write-and-share',
        'part-9-build-deploy-show/referrals-network',
        'part-9-build-deploy-show/zero-to-hired',
      ],
    },
  ],
};

export default sidebars;
